"""
Django settings for test_blog project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yov5w#)pkt3ilm^j453s(vs9*5^jvj2m1-(%d0@xf21!40y(b&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'haystack',
    #django-ckeditor注册到该列表中
    'ckeditor',
    #注册富文本编辑器上传功能
    'ckeditor_uploader',
    'blog',
    'comments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'test_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'test_blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    #'default': {
        #数据库引擎，指明数据库类型
    #    'ENGINE': 'django.db.backends.sqlite3',
        #指明数据库所在位置，本项目中数据库位置：/myproject/db.sqlite3
    #    'NAME': BASE_DIR / 'db.sqlite3',
    #}
    'default':{
        'ENGINE' : 'django.db.backends.mysql',    #数据库引擎，指明数据库类型
        'HOST' : '127.0.0.1',   #数据库存储在本机
        'POST' : '3306',    #数据库端口号
        'NAME' : 'test_blog',  #数据库名称
        'USER' : 'root',    #数据库用户名
        'PASSWORD' : '123456',  #数据库密码
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CKEDITOR_CONFIGS = {
    'default':{
        'language':'zh-cn',
        'width':'660px',
        'height':'200px',
        #设置工具栏为自定义，名字为Custom
        'tpplbar':'Custom',
        #添加富文本编辑器的工具栏上的按钮
        'toolbar_Custom':[
            ['Bold','Italic','UnderLine'],
            ['NumberedList','BulletedList'],
            ['Image','Link','Unlink'],
            ['Maximize'],
        ]
    }
}

HAYSTACK_CONNECTIONS = {
    'default' : {
        #指定Django Haystack要使用的搜索引擎，whoosh_backend_cn就是我们修改的文件
        'ENGINE' : 'blog.whoosh_backend_cn.WhooshEngine',
        #'ENGINE' : 'haystack.backends.whoosh_backend.WhooshEngine',
        #指定文件存放在路径
        'PATH' : os.path.join(BASE_DIR,'whoosh_index'),
        'INCLUDE_SPELLING': True,
    },
}
#指定搜索结果分页方式为每页六条记录
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 6
#指定实时更新索引，当有数据改变时，自动更新索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

#设置认证系统使用的用户模型，这里指定认证系统的用户模型的位置，是博客应用程序的loguser
AUTH_USER_MODEL = 'blog.loguser'

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'   #语言格式

TIME_ZONE = 'Asia/Shanghai'  #设置时区

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
#CKEDITOR_UPLOAD_PATH设置富文本编辑器的上传文件的相对路径
CKEDITOR_UPLOAD_PATH = 'upload/'
CKEDITOR_UPLOAD_BACKEND = 'pillow'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
